name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write # Required by hetznercloud/tps-action

    defaults:
      run:
        working-directory: example

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2
        with:
          tofu_version: v1.12.0 # renovate: datasource=github-releases depName=opentofu/opentofu
          tofu_wrapper: false

      - uses: yokawasa/action-setup-kube-tools@9d39563c24d4a419d1a8289c34d6da5a6171252c # v0.13.5
        with:
          setup-tools: |
            kubectl
            skaffold
          kubectl: v1.36.1 # renovate: datasource=github-releases depName=kubernetes/kubernetes
          skaffold: v2.21.0 # renovate: datasource=github-releases depName=GoogleContainerTools/skaffold

      - name: Setup k3sup
        env:
          K3SUP_VERSION: 0.13.12 # renovate: datasource=github-releases depName=alexellis/k3sup
        run: |
          curl https://github.com/alexellis/k3sup/releases/download/$K3SUP_VERSION/k3sup -sSL -o /usr/local/bin/k3sup
          chmod +x /usr/local/bin/k3sup

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: test-app/go.mod

      - uses: hetznercloud/tps-action@dc6d67c5768ca43b840429b6c7409cda61cf4092 # main

      - name: Swap module source
        run: sed -i -e 's|source = ".*"|source = "./.."|' main.tf

      - name: Setup environment
        run: make up

      - name: Verify environment
        run: |
          source files/env.sh

          kubectl wait --for=condition=Ready --all node
          kubectl wait --for=condition=Available --all --all-namespaces deployment
          kubectl wait --for=condition=Ready --all --all-namespaces pod

      - name: Deploy test app
        working-directory: test-app
        run: |
          source ../example/files/env.sh

          skaffold run
          kubectl wait --for=condition=Ready --all pod -l app=test-app

      - name: Cleanup
        if: always()
        run: make down
